export enum TipoServico {
  ARTE = "ARTE",
  GRAFICA_RAPIDA = "GRAFICA_RAPIDA",
  IMPRESSAO_DIGITAL = "IMPRESSAO_DIGITAL",
  COMUNICACAO_VISUAL = "COMUNICACAO_VISUAL",
  TERCEIRIZADO = "TERCEIRIZADO"
}

export enum SubTipoServico {
  IMPRESSAO_RAPIDA = "IMPRESSAO_RAPIDA",
  IMPRESSAO_COM_ACABAMENTO = "IMPRESSAO_COM_ACABAMENTO",
  CARIMBO = "CARIMBO",
  ACABAMENTO = "ACABAMENTO",
  PLACA_SIMPLES = "PLACA_SIMPLES",
  PLACA_COMPLEXA = "PLACA_COMPLEXA"
}
